/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AD_T1_C_Xml;

import java.io.File;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 *
 * @author Vespertino
 */
public class Ej7Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ej72
     */
    public Ej7Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        introducirDatos = new javax.swing.JTextField();
        texto = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Introduce el departamento : ");

        Buscar.setText("Buscar");
        Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(introducirDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Buscar)))
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(introducirDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarMouseClicked
        //Creamos una factoria
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        //guardamos los datos del textbox en un string
        String dep_num = introducirDatos.getText();

        try {
            //Las tres siguientes lineas hay que declararlas para la lectura del xml
            DocumentBuilder builder = factory.newDocumentBuilder();
            Document document = builder.parse(new File("Departamentos.xml"));
            document.getDocumentElement().normalize();

            //Muestra el elemento raiz del documento que seria "Departementos"
            System.out.printf("Elemento raiz: %s %n", document.getDocumentElement().getNodeName());

            //crea una lista con todos los nodos departamentos 
            NodeList departamentos = document.getElementsByTagName("Departamento");
            //numero de empleados en cada nodo departamento
            System.out.printf("Nodos empleado a recorrer: %d %n", departamentos.getLength());

            //recorrer la lista  
            for (int i = 0; i < departamentos.getLength(); i++) {
                Node depart = departamentos.item(i); //obtener un nodo departamento
                Node emple = departamentos.item(i); //obtener un nodo empleado
                if (depart.getNodeType() == Node.ELEMENT_NODE) {//tipo de nodo
                    //obtener los elementos del nodo           
                    Element elemento = (Element) depart;
                    //introduce los datos del departamento en el textArea
                    if (elemento.getElementsByTagName("dept_no").item(0).getTextContent().equals(dep_num)) {
                        texto.setText( "DEPARTAMENTO" +"\n");
                        texto.setText(texto.getText() + "Dept_no = " + elemento.getElementsByTagName("dept_no").item(0).getTextContent()+"\n");
                        texto.setText(texto.getText() + " * Nombre = " + elemento.getElementsByTagName("nombre").item(0).getTextContent()+"\n");
                        texto.setText(texto.getText() + " * Localidad = " + elemento.getElementsByTagName("localidad").item(0).getTextContent()+"\n");
                        //obtener los elementos del nodo           
                        Element elemento2 = (Element) emple;
                        texto.setText(texto.getText() + "EMPLEADO" +"\n");
                        texto.setText(texto.getText() + "Emp_num = " + elemento2.getElementsByTagName("emp_num").item(0).getTextContent()+"\n");
                        texto.setText(texto.getText() + " * Apellido = " + elemento2.getElementsByTagName("apellido").item(0).getTextContent()+"\n");
                        texto.setText(texto.getText() + "  \n");
                        break;
                    }else if (i == departamentos.getLength()-1){
                        texto.setText("EL INDICADO DEPARTAMENTO NO EXISTE\n");
                    } 
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej7Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej7Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej7Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej7Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ej7Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField introducirDatos;
    private javax.swing.JLabel jLabel1;
    private java.awt.TextArea texto;
    // End of variables declaration//GEN-END:variables
}
